name: .NET

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet: [8.0.x]
        framework: [net6.0, net7.0, net8.0]
        os: [windows-latest]
        config: [Any CPU]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c ${{ matrix.config }} --no-restore --verbosity normal --framework ${{ matrix.framework }}
