name: .NET

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet: [8.x]
        framework: [net6.0-windows, net7.0-windows, net8.0-windows]
        os: [windows-latest]
        platform: [Any CPU]
        config: [Debug, Release]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.config }} [${{ matrix.framework }}]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          cache: true
          cache-dependency-path: MarkMpn.FetchXmlToWebAPI.Tests/packages.lock.json

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      # The '--graph' parameter is to address an occasional build error about files being
      # used by another process the during 'GenerateRuntimeConfigurationFiles'
      # task: https://github.com/dotnet/msbuild/issues/6690#issuecomment-1553272562
      - name: Build
        run: dotnet build --graph -c "${{ matrix.config }}" -p:Platform="${{ matrix.platform }}" --framework "${{ matrix.framework }}" --no-restore --verbosity normal

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration "${{ matrix.config }}" --framework "${{ matrix.framework }}" --collect:"XPlat Code Coverage" --results-directory:.build/TestResults --logger:trx
